### ISSUE TITLE
How to best recover biffboot

### ISSUE THREAD

**Issue by Risca** [bifferos/bb#7]
Ok, so I messed up.

### Background
I got a Meteoplug client, based on the dual USB Bifferboard, from a colleague at work and I've been tampering with it for the past few weeks. My plan is to use it as a printer server at home. I've mostly been using qemu to test stuff, and it's been going well. I've made some changes to biffboot as well, to better support my software upgrade scenario. It all runs splendid in qemu :sweat_smile: 

### What went wrong
I decided it was time to test my custom `biffboot.bin` on the real thing, so I launched a custom image through TFTP and basically ran:
```
# cat /proc/mtd
dev:    size   erasesize  name
mtd0: 00200000 00010000 "kernel"
mtd1: 005f0000 00010000 "rootfs"
mtd2: 00010000 00010000 "biffboot"
# nc -l -p 9899 > /tmp/biffboot.bin
# md5sum /tmp/biffboot.bin
# cat /tmp/biffboot.bin > /dev/mtdblock2
# reboot
```

Now, my console output is all scrambled when I try to power on the board :( It tries to print _something_ to the console, but it's impossible to decipher. I haven't hooked up an oscilloscope yet to try and guess the correct baud rate (if any)

### What to do now?
So, I would need some help. I've read that the Bifferboard can be programmed using JTAG (and a proprietary protocol?):
* Did you have any more Bifferboards for sale? :slightly_smiling_face: I've seen that they can be used as programmers!
* I have other hardware at home. Can a Raspberry Pi or a C.H.I.P. board be used as a JTAG programmer?
* A PIC or AVR MCU maybe?

### Additional input

My changes to biffboot: https://github.com/Risca/biffboot/tree/minor_fixes
Is there any other information I should provide that could assist here?

**Comment by Risca** [comment]
I don't really know why my bootloader doesn't work on the real HW, but it works in QEMU. It is _possible_ that it's related to DRAM buffer strength. I did a dump of the original biffboot before flashing (for comparison), but it doesn't seem to have this setting in its config section at the end of the file.

**Comment by lurch** [comment]
I don't mean any disrespect (back in the day, I was a keen contributor to the bifferboard project), but given the "dead end" nature of the hardware, why do active development using bifferboard and not one of the many cheap ARM SBCs available?

Of course for some people "I wanted to try something that's _not_ a cheap ARM SBC" is a valid answer in itself :wink: 

(@bifferos Feel free to delete my comment if you feel that it's inappropriate)

**Comment by bifferos** [comment]
Hi Lurch, comments from you are never going to be inappropriate.  How ya doin me ole' mate?

Bifferboard does have some advantages over other platforms:
- Form factor (if you want that)
- Bomb proof (I just leave them running for literally years without issue, the few Pis that I've deployed have all gone wrong after some months.
- Barrel connector for power (I *hate* USB connections for this, feels less substantial).

And also, I have a few of them, many more than the Pis I've bought.

**Comment by bifferos** [comment]
@Risca you probably need to setup jtag.  You can join two boards together and program one from the other.
https://github.com/bifferos/biffjtag
That was the old version, using Nasm the new version is combined with busybox.
Instructions on how to make a Jtag-programming 1MB firmware are here:
https://github.com/bifferos/bb/tree/master/tiny
The busybox biffjtag is here:
https://github.com/bifferos/bb/tree/master/tiny/busybox-1.22.1/gpio
If you trust my binaries you may save some time using my toolchain:
https://github.com/bifferos/bb/releases

If you want to program a bifferboard from a parallel port jtag setup (assuming you want to make the hardware and have the port itself on your PC), code here:
https://github.com/bifferos/bb/tree/master/tools/jtag
And hardware looks like this:
https://github.com/bifferos/bb/blob/master/tools/jtag/bifferboard_jtag.png

You may wonder why you can't just use Arduino or something to program the Bifferboard over JTAG, and it's a great question because I have no clue about the answer.  I think there is some timing issue that I never worked out.  In fact at one point, I had an AVR between the PC and a board being programmed just relaying the signals and that worked fine, but once I moved the software into the AVR, nothing worked.  It seems to rely on ISA bus timing that you get from either a Bifferboard JTAG or a real parallel port.

As for boards, sure I have loads, you can connect with me at bifferos@gmail.com.  Maybe I can even make you a cable if you want, but if you have one working Bifferboard there could be other ways.

Finally, I don't think your problem is buffer strength from what you describe, that value I believe is only important once Linux is running IIRC and only after some time.  You should get a boot regardless.

**Comment by lurch** [comment]
> Hi Lurch, comments from you are never going to be inappropriate. How ya doin me ole' mate?

Haha cool. I'm good thanks, now working for an "ARM SBC" company - see my [profile](https://github.com/lurch) :wink: 

> I don't really know why my bootloader doesn't work on the real HW

IIRC there are some x86 instructions that the CPU in the bifferboard doesn't support, so if you've not set the right compiler-options maybe there's an instruction in your biffboot binary that the bifferboard's CPU can't execute?
And in general it's always good idea to set up and test your fail-safe option (i.e. JTAG) first, before making a change as severe as flashing a new firmware. Live & learn.

**Comment by bifferos** [comment]
181 repos?  Are you kidding me?  That's not work more like a lifestyle choice :).  Tell them to get a nice barrel power connector and on-board NOR flash... and a proper bootloader instead of this FAT loader thingy then I'd have been much more interested.  Always had problems with SD cards, even good quality ones.  I just don't want my boot path to go over a spring-loaded connector, it just feels wrong.  I mean, I can see why they did it, but anyway.

I don't honestly think this is about instruction sets.  If Risca got a compile chances are he's got the right toolchain.  So long as Qemu is set to 486 instructions (You did do that didn't you Risca?), then that should be tested, except for the fact that Qemu can't select between 486SX vs DX, but biffboot doesn't (didn't?) use floating point.
Testing the original biffboot with this flashing method would have been a smart move.  Did that work?  If that wasn't tested then not much we can do now.
I think mtdblock2 may not be the top of flash somehow.  Or the other thing that may have happened with the block driver is that it wrote only the bottom portion of the bootloader, but left the JMP instruction at the top of ram untouched, so the JMP jumped into the garbage that was written below.  All theories of course really needs jtag to dump what's there.  Or is that writing to a partition instead of an area (sequence of sectors) of the flash?

Also Risca, I had a brief look at the changes to biffboot, far be it for me to tell you what to do, but if you want some better update capability did you consider doing this inside Linux instead?  There are kernel drivers for updating the NOR flash and you could update the configuration (e.g. command-line) if needed.  It may be more convenient to put this kind of thing inside a busybox applet than write it into Biffboot.  Although Biffboot is more low-level therefore likely to be more fun :).

**Comment by Risca** [comment]
Wow, I did _not_ expect such quick response to this!

> I don't mean any disrespect (back in the day, I was a keen contributor to the bifferboard project), but given the "dead end" nature of the hardware, why do active development using bifferboard and not one of the many cheap ARM SBCs available?
> 
> Of course for some people "I wanted to try something that's _not_ a cheap ARM SBC" is a valid answer in itself :wink: 

I'm actually replacing the Raspberry Pi I have _already_ setup for this :laughing: I just didn't want this hardware to go to waste, and now I'm already in too deep :sweat_smile: I keep telling myself that if I succeed, then I can repurpose the Raspberry Pi for something else...

I'm having fun, though :smiley: I enjoy a challenge. Nowhere near 181 repos, though (only 61 ^^)

> So long as Qemu is set to 486 instructions (You did do that didn't you Risca?), then that should be tested, except for the fact that Qemu can't select between 486SX vs DX, but biffboot doesn't (didn't?) use floating point.

Yes, should be 486. This is how I launched qemu from bb repo:
```
../bb/qemu/i386-softmmu/qemu -cpu 486 -m 32 -bios ../biffboot/biffboot.bin -rtc base="$(date -u +%Y-%m-%dT%H:%M:%S)" -firmware output/images/qemu.img -vga none -nographic -net nic,model=r6040,macaddr=52:54:00:12:34:57,vlan=0 -net user,vlan=0,hostfwd=tcp:127.0.0.1:6631-:631
```

Qemu was sometimes giving me segfaults, so I ported some of the qemu changes from the bb repo to qemu-5.2.0 and it continued to work. This is how I launched qemu-5.2.0:
```
./output/host/bin/qemu-system-i386 -machine rdc3210 -cpu 486 -vga none -nographic -usb -device usb-storage,bus=usb-bus.0,drive=sda -drive file=../bb/usbdisk.img,if=none,id=sda,format=raw -netdev user,id=eth0,hostfwd=tcp:127.0.0.1:6631-:631 -device r6040,netdev=eth0,mac=52:54:00:12:34:57,addr="08.0" -bios ../biffboot/biffboot.bin -m 32 -no-acpi -no-hpet
```
It's hardcoded to read "qemu.img" for the flash/firmware content. I should fix that. Sorry, no sources/patches pushed yet.

> Testing the original biffboot with this flashing method would have been a smart move. Did that work? If that wasn't tested then not much we can do now.

Agreed, that _would_ have been smart :sweat_smile: I didn't have any official biffboot binaries, but I _could_ have used the biffboot I dumped from flash before overwriting it.

> I think mtdblock2 may not be the top of flash somehow. Or the other thing that may have happened with the block driver is that it wrote only the bottom portion of the bootloader, but left the JMP instruction at the top of flash untouched, so the JMP jumped into the garbage that was written below. All theories of course really needs jtag to dump what's there. Or is that writing to a partition instead of an area (sequence of sectors) of the flash?

Writing to `mtdblock2` should write directly to flash sectors. I felt "confident" that my trick would work because the dump of `mtdblock2` looked very similar to what my own biffboot looked like. Both were 64K, `file` reported "DOS executable (COM)", they both had MAC address at the bottom, and my biffboot worked with qemu :shrug: 
I wasn't aware of the `JMP` instruction at the top :sweat_smile: 

> Also Risca, I had a brief look at the changes to biffboot, far be it for me to tell you what to do, but if you want some better update capability did you consider doing this inside Linux instead? There are kernel drivers for updating the NOR flash and you could update the configuration (e.g. command-line) if needed. It may be more convenient to put this kind of thing inside a busybox applet than write it into Biffboot. Although Biffboot is more low-level therefore likely to be more fun :).

I have most of my boards at home integrated with Mender (https://mender.io/) for software updates. Mender works by having 2 partitions - the active and the inactive. You flash the inactive partition, make some changes in config, and reboot.

For my printer server, I quickly realized I _need_ my rootfs to be located on a  SD card - `gs` itself (stripped) is 12 whopping MB! My solution, which is working in QEMU btw, was to update biffboot so it adjusts the cmdline parameter and then launch a bootstrap application from flash. This bootstrap only has the bare minimal required to mount `${root}` from cmdline and then `kexec` away! I think I got it down to 784 KB last time I checked :smile:

For the whole upgrade process to work though, both biffboot and Linux needs to be able to update the config area. Therefore, I made my own "clones" of the U-boot `fw_printenv` and `fw_setenv` tools, which is what the mender client uses. Code is here: https://github.com/Risca/bb_env

(The mender client is written in Go. Don't get me started on how much time it took to get a go compiler to work for 486)

> As for boards, sure I have loads, you can connect with me at bifferos@gmail.com. Maybe I can even make you a cable if you want, but if you have one working Bifferboard there could be other ways.

I only had the 1 board. As tempting as it is to get my own JTAG working, I figure it would be easier to just go with something that is known working. You've got mail :wink:

**Comment by Risca** [comment]
I did consider that, but then I have a dependency on another machine and I don't really like that ^^ Becomes extra hairy after a power outage (or when you blow a fuse for some reason :innocent: )

**Comment by lurch** [comment]
> 181 repos? Are you kidding me? That's not work more like a lifestyle choice :)

I'm one of those annoyingly pedantic (helpful?) people, where if I see a typo in someone's repo I'll fork it and submit a PR. And then never get round to deleting the forked repo...

> Tell them to get a nice barrel power connector and on-board NOR flash

https://www.raspberrypi.com/products/compute-module-4-io-board/ :slightly_smiling_face: 

> and now I'm already in too deep

LOL, fair enough :grin:

**Comment by bifferos** [comment]
> I did consider that, but then I have a dependency on another machine and I don't really like that ^^ Becomes extra hairy after a power outage (or when you blow a fuse for some reason innocent )

Totally understand.  If you want to get the Qemu patches moved to the latest Qemu 5.2 I'd be interested in helping. I think I bottled out because I thought it was too much work but if you've started and you're interested in using it that changes a lot.

**Comment by Risca** [comment]
Not sure how much work it's worth. Mind you, this _is_ a hobby project. I've put up my current working patch for qemu-5.2.0 here:
https://gist.github.com/Risca/5c52f5cd17c4e6e91785d7ba9ef8adc5

Instead of porting _en29lv640.c_, I found that I only had to make some minor changes to _pflash_cfi02.c_ to make flash detection work. I added a new machine type called "rdc3210", based on _pc_piix.c_. Porting of _r6040.c_ was fairly trivial :slightly_smiling_face: I haven't ported the gpio stuff. Also did some hacking in _i440fx.c_ and _cpu.h_ for the final touches

**Comment by Risca** [comment]
> Not sure how much work it's worth. Mind you, this _is_ a hobby project. I've put up my current working patch for qemu-5.2.0 here: https://gist.github.com/Risca/5c52f5cd17c4e6e91785d7ba9ef8adc5

Just updated the patch so biffboot is read from the flash backing file :wink:

**Comment by Risca** [comment]
I received a little care package from @bifferos today and was able to flash my BifferBoard with a Turbo NAS card and `biffjtag`.

I guess that means this issue can be closed. Thank you all for the help :smiley:

Now, I can go figure out why my biffboot didn't boot...

**Comment by Risca** [comment]
A quick bisect and I found the issue:
```diff
diff --git a/flashmap.h b/flashmap.h
index 7dcd25e..3d8d345 100644
--- a/flashmap.h
+++ b/flashmap.h
@@ -20,7 +20,7 @@ extern u32 FLASHMAP_CHUNK_COUNT;
 // flash detection codes.
 #define FLASH_CODE_EN800 (0x7f1c225b)
 #define FLASH_CODE_EN320 (0x7f1c22f9)
-#define FLASH_CODE_EN640 (0x7f1c22cb)
+#define FLASH_CODE_EN640 (0x7f1c00cb)
 
 
 // the flash detected during init.
```
I couldn't make qemu (5.2 _and_ from this repo) to work with biffboot unless I made this change, but it inadvertently made the real hardware not boot!
